nav_brand: "Moreland Playbook"
hero:
  title: "Moreland Connect Playbook"
  subtitle: "From Vision to Victory"
  description: "Your comprehensive guide to running world-class design sprints. Two proven playbooks to take ideas from concept to market-ready solutions, with the depth and precision of Thoughtbot's methodology."
